In [223]:
import pandas as pd
import numpy as np
import json
pd.set_option('display.max_columns', None)


In [ ]:
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

In [198]:
folder_path = 'toni_data_2609/'

In [243]:
politicians = pd.read_csv(f'{folder_path}politicians.csv')
print(len(politicians))
politicians = politicians[politicians['electoral_term'].isin([19, 20])]
print(len(politicians))

politicians = pd.merge(politicians, party, left_on='faction_id', right_on='id', how='left')

# removing duplicates
print(len(politicians))
politicians = politicians.drop_duplicates()
print(len(politicians))

# removing politicians without abbreviation
# Only one entry per electoral term stays, all "Ausschüsse" or other entries are removed
politicians = politicians.dropna(subset=['abbreviation'])

# Step 1: Filter for "Regierungsmitglied"
regierungsmitglieder = politicians[politicians['institution_type'] == 'Regierungsmitglied']

# Step 2: Remove duplicates based on 'politician_id' and 'electoral_term'
unique_regierungsmitglieder = regierungsmitglieder.drop_duplicates(subset=['ui', 'electoral_term'])

# Optional: If you want to keep all original columns in datacube
# You can merge this back if necessary or just assign it to datacube
politicians = politicians[~politicians['ui'].isin(unique_regierungsmitglieder['ui'])]  # Remove existing duplicates
politicians = pd.concat([politicians, unique_regierungsmitglieder])  # Combine back
print(len(politicians))

unique_combinations = politicians[['ui', 'electoral_term']].drop_duplicates()
print('unique politicians per electoral period before dupl removal:', len(unique_combinations))


# remove duplications: keep one name if namechange (marriage), keep only longest academic title if multiple, keep only one faction if multiple
# Step 1: Function to consolidate values, including longest title, actual faction, institution name, and name streamlining
def consolidate_group(group):
    # 1. Longest academic title
    longest_title_idx = group['academic_title'].dropna().str.len().idxmax() if not group['academic_title'].dropna().empty else None
    if longest_title_idx is not None:
        longest_title = group.loc[longest_title_idx, 'academic_title']
        group['academic_title'] = group['academic_title'].fillna(longest_title)  # Fill if we found a valid longest title

    # 2. Faction: prefer entries with a valid faction (i.e., non-null faction_id and non-Fraktionslos)
    valid_faction = group.loc[group['faction_id'].notnull() & (group['abbreviation'] != 'Fraktionslos')]
    if not valid_faction.empty:
        valid_faction_row = valid_faction.iloc[0]  # Take the first valid faction row
        group['faction_id'] = group['faction_id'].fillna(valid_faction_row['faction_id'])
        group['abbreviation'] = group['abbreviation'].fillna(valid_faction_row['abbreviation'])
        group['institution_name'] = group['institution_name'].fillna(valid_faction_row['institution_name'])

    # 3. Streamline names: prioritize the most recent last name and first name
    most_recent_entry = group.iloc[-1]  # Take the most recent entry as the baseline for names
    group['last_name'] = group['last_name'].fillna(most_recent_entry['last_name'])
    group['first_name'] = group['first_name'].fillna(most_recent_entry['first_name'])

    return group

# Step 2: Apply the function, grouping by both 'ui' and 'electoral_term'
politicians = politicians.groupby(['ui', 'electoral_term']).apply(consolidate_group)

# Optional: Reset index if needed
politicians.reset_index(drop=True, inplace=True)

# Step 3: Drop duplicates within each group, keeping the relevant rows
politicians = politicians.drop_duplicates(subset=['ui', 'electoral_term'], keep='first')

unique_combinations = politicians[['ui', 'electoral_term']].drop_duplicates()
print('unique politicians after dupl removal:', len(unique_combinations))


# 7 OCT 2024 

# WE NEED TENURE ! (maybe year since first speach??)

# pro person brauchen wir nur eine speech. Zwischenrufe rausgefiltert? ist die speech gesplitted in mehrere Teile vor und nach 
# Zwischenrufen?

# reden sind in viele Teile gesplitted, die wir zusammenfügen müssen


politicians.sample(10)

19632
6706
6706
6067
1690
unique politicians per electoral period before dupl removal: 1537
unique politicians after dupl removal: 1537


ui  electoral_term  faction_id first_name       last_name  \
1100  11004797              19          15  Alexander          Kulitz   
314   11003837              19           4    Gerhard          Schick   
1647  11005258              20           5     Tobias         Winkler   
1655  11005264              20           0    Joachim         Wundrak   
870   11004660              19           7     Simone      Barrientos   
706   11004353              20           4      Irene         Mihalic   
53    11002667              20           5    Manfred           Grund   
1096  11004793              19           5  Alexander           Krauß   
942   11004703              20           7       Anke  Domscheit-Berg   
1552  11005168              20          25      Brian        Nickholz   

               birth_place birth_country  birth_date death_date    gender  \
1100              Tübingen   Deutschland  12.08.1981         -1  männlich   
314              Hechingen   Deutschland  18.04.1972         -1  männlich   
1647              Nürnberg   Deutschland  16.01.1978         -1  männlich   
1655                  Buir   Deutschland  28.05.1955         -1  männlich   
870   Lutherstadt Eisleben   Deutschland  05.10.1963         -1  weiblich   
706               Waldbröl   Deutschland  17.11.1976         -1  weiblich   
53                   Zeitz   Deutschland  03.07.1955         -1  männlich   
1096             Erlabrunn   Deutschland  08.12.1975         -1  männlich   
942               Premnitz   Deutschland  17.02.1968         -1  weiblich   
1552         Gelsenkirchen   Deutschland  22.12.1989         -1  männlich   

                                       profession constituency aristocracy  \
1100                                  Unternehmer          NaN         NaN   
314                                     Volkswirt          NaN         NaN   
1647                                   EU-Beamter          NaN         NaN   
1655                        Generalleutnant a. D.          NaN         NaN   
870   Elektrikerin, Gebrauchswerberin, Verlegerin          NaN         NaN   
706                                Polizeibeamtin          NaN         NaN   
53                               Elektroingenieur          NaN         NaN   
1096                       Politikwissenschaftler          NaN         NaN   
942                                   Publizistin          NaN         NaN   
1552                            Industriekaufmann          NaN         NaN   

     academic_title institution_type  \
1100            NaN  Fraktion/Gruppe   
314             Dr.  Fraktion/Gruppe   
1647            NaN  Fraktion/Gruppe   
1655            NaN  Fraktion/Gruppe   
870             NaN  Fraktion/Gruppe   
706             Dr.  Fraktion/Gruppe   
53              NaN  Fraktion/Gruppe   
1096            NaN  Fraktion/Gruppe   
942             NaN  Fraktion/Gruppe   
1552            NaN  Fraktion/Gruppe   

                                       institution_name    id  \
1100          Fraktion der Freien Demokratischen Partei  15.0   
314                      Fraktion BÜNDNIS 90/DIE GRÜNEN   4.0   
1647  Fraktion der Christlich Demokratischen Union/C...   5.0   
1655               Fraktion Alternative für Deutschland   0.0   
870                                 Fraktion DIE LINKE.   7.0   
706                      Fraktion BÜNDNIS 90/DIE GRÜNEN   4.0   
53    Fraktion der Christlich Demokratischen Union/C...   5.0   
1096  Fraktion der Christlich Demokratischen Union/C...   5.0   
942                                 Fraktion DIE LINKE.   7.0   
1552  Fraktion der Sozialdemokratischen Partei Deuts...  25.0   

               abbreviation  
1100                    FDP  
314   Bündnis 90/Die Grünen  
1647                CDU/CSU  
1655                    AfD  
870              DIE LINKE.  
706   Bündnis 90/Die Grünen  
53                  CDU/CSU  
1096                CDU/CSU  
942              DIE LINKE.  
1552                    SPD

In [193]:
politicians[politicians['ui'] == 11003702]

# lemke 11002720
# wissing 11003702


# save this as excel file 
politicians['institution_name'].value_counts().to_excel('politicians_institution_name.xlsx')



politicians['abbreviation'].value_counts()


politicians[politicians['last_name'] == 'Wagenknecht']


#politicians[politicians['faction_id'] != -1]['institution_name'].value_counts().to_excel('politicians_institution_name_with_faction.xlsx')
politicians[politicians['ui'] == 11003702]

# für wie viele Fälle haben politiker reden gehalten die garnicht im bundestag gerade sind?? 

# lemke 11002720
# wissing 11003702


politicians[(politicians['institution_type'] == 'Regierungsmitglied') & (politicians['id'] == 18)].head()
# beide einträge falsch 

politicians[(politicians['faction_id'] == 18) & (politicians['electoral_term'] == 20)][['first_name', 'last_name']]

politicians.columns

ui  electoral_term  faction_id first_name last_name  \
6668  11002720              19          18     Steffi     Lemke   
6703  11003702              19          18     Volker   Wissing   

         birth_place birth_country  birth_date death_date    gender  \
6668          Dessau   Deutschland  19.01.1968         -1  weiblich   
6703  Landau / Pfalz   Deutschland  22.04.1970         -1  männlich   

                  profession constituency aristocracy academic_title  \
6668  Dipl.-Agraringenieurin          NaN         NaN            NaN   
6703            Rechtsanwalt          NaN         NaN            Dr.   

        institution_type                                   institution_name  \
6668  Regierungsmitglied  Umwelt, Naturschutz, nukleare Sicherheit und V...   
6703  Regierungsmitglied                              Digitales und Verkehr   

        id  abbreviation  
6668  18.0  Fraktionslos  
6703  18.0  Fraktionslos

In [278]:

# Step 1: Load speech content and prepare the data
speech_content = pd.read_pickle(f'{folder_path}speech_content.pkl')
speech_content['date'] = pd.to_datetime(speech_content['date'], unit='s')
speech_content = speech_content.sort_values('date')

# Standardize first_name and last_name by stripping whitespace and converting to lowercase
speech_content['first_name'] = speech_content['first_name'].str.strip().str.lower()
speech_content['last_name'] = speech_content['last_name'].str.strip().str.lower()

# Step 2: Find the most frequently occurring politician_id for each first_name and last_name as canonical politician_id
politician_id_counts = speech_content.groupby(['first_name', 'last_name', 'politician_id']).size().reset_index(name='count')
most_frequent_id = politician_id_counts.sort_values('count', ascending=False).drop_duplicates(subset=['first_name', 'last_name'])

# Step 3: Merge the canonical politician_id back into the speech_content DataFrame
corrected_speech_content = speech_content.merge(most_frequent_id[['first_name', 'last_name', 'politician_id']], 
                                                on=['first_name', 'last_name'], how='left', suffixes=('', '_canonical'))

# Step 4: Replace all politician_ids with the canonical (most frequent) politician_id
corrected_speech_content['politician_id'] = corrected_speech_content['politician_id_canonical'].combine_first(corrected_speech_content['politician_id'])

# Step 5: Drop unnecessary columns
corrected_speech_content.drop(columns=['politician_id_canonical'], inplace=True)

# Step 6: Merge corrected_speech_content with politicians DataFrame
# Ensure the politicians DataFrame is loaded and standardized similarly
politicians = politicians[['ui', 'electoral_term', 'faction_id', 'abbreviation', 'first_name', 'last_name', 'birth_place', 'birth_country',
                           'birth_date', 'death_date', 'gender', 'profession', 'academic_title', 'institution_type', 'institution_name']]

politicians['first_name'] = politicians['first_name'].str.strip().str.lower()
politicians['last_name'] = politicians['last_name'].str.strip().str.lower()

# Perform the merge
datacube = corrected_speech_content.merge(politicians, left_on=['politician_id', 'electoral_term'], 
                                          right_on=['ui', 'electoral_term'], how='left')

# Step 7: Count matches and entries without politician information after the merge
matches = datacube['ui'].notnull().sum()
remaining_without_politician_info = datacube['ui'].isnull().sum()

# Output results
print(f"Total matches found: {matches}")
print(f"Total speech entries without politician information: {remaining_without_politician_info}")

# Step 8: Filter for electoral terms 19 and 20 and prepare the final datacube
datacube = datacube[datacube['electoral_term'].isin([19, 20])]
datacube = datacube.sort_values('date')
datacube = datacube[['id', 'electoral_term', 'session', 
                     'first_name_x', 'last_name_x', 'faction_id_x', 'politician_id', 
                     'position_short', 'position_long', 
                     'speech_content', 'date']]

# Step 9: Check for duplicates after merging (optional)
duplicate_count = datacube.duplicated(subset=['id', 'politician_id', 'electoral_term']).sum()
print(f"Number of duplicates in datacube: {duplicate_count}")

# Step 10: Remove speech content entries where content is empty or whitespace
empty_or_whitespace_mask = datacube['speech_content'].str.strip() == ''
datacube = datacube[~empty_or_whitespace_mask]

# Step 11: Count total entries in datacube before the final merge
total_entries_before_merge = len(datacube)

# Step 12: Final merge of datacube with politicians DataFrame
datacube = datacube.merge(politicians, left_on=['politician_id', 'electoral_term'], right_on=['ui', 'electoral_term'], how='left')

# Step 13: Count matches where politician information is found and entries without politician information
matches = datacube['ui'].notnull().sum()
remaining_without_politician_info = datacube['ui'].isnull().sum()

# Final output
print(f"Total speech entries before merge: {total_entries_before_merge}")
print(f"Total matches found: {matches}")
print(f"Total speech entries without politician information: {remaining_without_politician_info}")


Total matches found: 116235
Total speech entries without politician information: 850769
Number of duplicates in datacube: 0
Total speech entries before merge: 120309
Total matches found: 116226
Total speech entries without politician information: 4083


In [283]:
# Step 1: Get successfully matched politicians
matched_politicians = datacube[datacube['ui'].notnull()][['politician_id', 'first_name_x', 'last_name_x']].drop_duplicates()

# Step 2: Find entries in speech_content with different politician_ids but same first/last name
# Merge speech_content with matched_politicians on first_name and last_name to find potential duplicates
duplicates_check = speech_content.merge(matched_politicians, left_on=['first_name', 'last_name'], 
                                        right_on=['first_name_x', 'last_name_x'], how='inner', suffixes=('', '_matched'))

# Step 3: Filter for cases where the politician_id in speech_content differs from the matched politician_id
potential_duplicates = duplicates_check[duplicates_check['politician_id'] != duplicates_check['politician_id_matched']]

# Step 4: Output the results
print(f"Number of potential duplicates: {len(potential_duplicates)}")
potential_duplicates[['politician_id', 'first_name', 'last_name', 'politician_id_matched']].drop_duplicates().head(20)

# If you want to investigate further, you can analyze more details of these potential duplicates


Number of potential duplicates: 426


politician_id  first_name  last_name  politician_id_matched
20808              -1       horst   seehofer               11002140
20809       999990075       horst   seehofer               11002140
37980        11002780      dagmar    schmidt               11004401
38722              -1       peter   altmaier               11002617
41075              -1       armin    laschet               11002718
44300              -1     hermann      gröhe               11002666
65147       999990073        olaf     scholz               11003231
65174              -1        olaf     scholz               11003231
67659              -1  hans-peter  friedrich               11003124
92055              -1   christine  lambrecht               11003167
98423       999990072       julia   klöckner               11003566
98428              -1       julia   klöckner               11003566
106246             -1       helge      braun               11003510
108085      999990079      volker    wissing               11003702
113456             -1      monika   grütters               11003761
127774             -1       armin   schuster               11004149
147188             -1      thomas   heilmann               11004741
154657      999980202        nina     warken               11004437
155913      999190001     carsten     träger               11004426
155914             -1     carsten     träger               11004426

In [265]:
politicians[(politicians['first_name'] == 'Boris') & (politicians['last_name'] == 'Pistorius')]

ui  electoral_term  faction_id abbreviation first_name  last_name  \
1685  11005328              19          25          SPD      Boris  Pistorius   

     birth_place birth_country birth_date death_date gender profession  \
1685         NaN           NaN       1960         -1    NaN        NaN   

     academic_title    institution_type institution_name  
1685            NaN  Regierungsmitglied     Verteidigung

In [277]:
no_match = datacube[datacube['ui'].isnull()][['first_name_x', 'last_name_x', 'electoral_term', 'politician_id']].drop_duplicates()

# sort no_match based on first and last name
no_match = no_match.sort_values(['first_name_x', 'last_name_x'])
no_match.head(30)

first_name_x             last_name_x  electoral_term  \
67886             andreas            bovenschulte              20   
9261              andreas                  geisel              19   
57897             andreas                pinkwart              19   
70448             andreas                pinkwart              20   
74505             andreas                 scheuer              20   
65418                anja               karliczek              20   
84550                anke               rehlinger              20   
64549            annalena                baerbock              20   
64531                anne                 spiegel              20   
27496            annegret       kramp-karrenbauer              19   
63481               armin                 laschet              19   
99572               armin                schuster              20   
40553                bela                    bach              19   
35628   benjamin-immanuel                    hoff              19   
86214             bettina                 jarasch              20   
118634               bodo                 ramelow              20   
37410               boris               pistorius              19   
84667               boris               pistorius              20   
101379           burkhard                blienert              20   
14546    carsten sieling,           bürgermeister              19   
64533                 cem                 özdemir              20   
42764           charlotte  schneidewind-hartnagel              19   
64555           christian                 lindner              20   
55781           christian                natterer              19   
64538           christine               lambrecht              20   
31417      christoph ploß               (cdu/csu)              19   
59947         christopher                    gohl              19   
84655              daniel                 rinkert              20   
99566             daniela                 behrens              20   
67193             dietmar                  woidke              20   

        politician_id  
67886              -1  
9261        999990076  
57897        11003610  
70448        11003610  
74505        11003625  
65418        11004323  
84550       999990133  
64549        11004245  
64531       999990122  
27496       999990083  
63481        11002718  
99572        11004149  
40553       999990092  
35628       999990091  
86214       999990137  
118634       11003824  
37410       999990093  
84667       999990093  
101379       11004254  
14546           10000  
64533        11002746  
42764              -1  
64555        11004097  
55781       999990104  
64538        11003167  
31417              -1  
59947       999990110  
84655       999990129  
99566              -1  
67193       999990082

In [215]:
datacube['institution_type'].value_counts()

institution_type
Fraktion/Gruppe       138147
Regierungsmitglied      4401
Name: count, dtype: int64

namensänderung (Agnieszka	Malczak	-> Agnieszka Brugger)

fraktion verlassen (Frank	Pasemann -> afd während periode verlassen)

verschiedene Titel (Hans	Michelbach -> Dr. h. c., Dr. h. c. (Univ Kyiv)	, nan)
(welchen nehmen? den längsten? was wenn dr. in dieser Zeit aberkannt?)
 
just remove duplicates 

many duplicate politicians so have to merge on multiple items! 
perfect when total speech entries before merge == total matches found! 


Building speech datacube 

each speaker:
- party (politicians table)
- fraction (yes no which one)
- member of parliament yes / no "MDB"
- electoral term (electoral_terms table)
 

contributions kategorisieren (wie viel beifall, wie viele zwischenrufe...)

In [246]:
# show me the entries where id appears more than one time
datacube[datacube['id'].duplicated(keep=False)].sort_values('id').head(20)

Empty DataFrame
Columns: [id, electoral_term, session, first_name_x, last_name_x, faction_id_x, politician_id, position_short, position_long, speech_content, date, ui, faction_id_y, abbreviation, first_name_y, last_name_y, birth_place, birth_country, birth_date, death_date, gender, profession, academic_title, institution_type, institution_name]
Index: []

In [282]:
missing_politicians = datacube[datacube['ui'].isnull()]
missing_politicians.sample(30)

#['politician_id'].value_counts()
#print(missing_politicians[['politician_id', 'speech_content']].head(20))  # Print first 10 missing entries


id  electoral_term  session first_name_x last_name_x  \
69910   1066139              20       30     annalena    baerbock   
77582   1092638              20       56         lisa        paus   
66247   1088873              20       15         lisa        paus   
75079   1087790              20       47         karl  lauterbach   
118634  1101363              20      182         bodo     ramelow   
92594   1078648              20      105         jens       spahn   
75582   1087199              20       49        klara     geywitz   
101309  1108994              20      130         lisa        paus   
39651   1059953              19      157       svenja     schulze   
79289   1068568              20       62       volker     wissing   
54534   1011967              19      208       svenja     schulze   
92754   1078615              20      105         karl  lauterbach   
120030  1075651              20      187       steffi       lemke   
117979  1075355              20      180         olaf      scholz   
83371   1113482              20       75        klara     geywitz   
99566   1097970              20      125      daniela     behrens   
91610   1078123              20      102     hubertus        heil   
39683   1059921              19      157       svenja     schulze   
83804   1086635              20       76         jens       spahn   
116823  1104612              20      177       robert      habeck   
93740   1108015              20      108          cem     özdemir   
9261    1055614              19       40      andreas      geisel   
98600   1098631              20      122        julia    klöckner   
115686  1075110              20      174       svenja     schulze   
73657   1114680              20       43    christine   lambrecht   
90564   1064123              20       99       steffi       lemke   
73640   1114631              20       43    christine   lambrecht   
67038   1119313              20       18     hubertus        heil   
73637   1114628              20       43    christine   lambrecht   
105561  1070761              20      143          cem     özdemir   

        faction_id_x  politician_id        position_short  \
69910             -1       11004245              Minister   
77582             -1       11004127              Minister   
66247              4       11004127  Member of Parliament   
75079             -1       11003797              Minister   
118634            -1       11003824                 Guest   
92594              5       11003638  Member of Parliament   
75582             -1      999990120              Minister   
101309            -1       11004127              Minister   
39651             -1      999990074              Minister   
79289             -1       11003702              Minister   
54534             -1      999990074              Minister   
92754             -1       11003797              Minister   
120030            -1       11002720              Minister   
117979            -1       11003231            Chancellor   
83371             -1      999990120              Minister   
99566             -1             -1              Minister   
91610             -1       11003142              Minister   
39683             -1      999990074              Minister   
83804             -1       11003638             Not found   
116823            -1       11005074              Minister   
93740             -1       11002746              Minister   
9261              -1      999990076                 Guest   
98600              5       11003566  Member of Parliament   
115686            -1      999990074              Minister   
73657             -1       11003167              Minister   
90564             -1       11002720              Minister   
73640             -1       11003167              Minister   
67038             -1       11003142              Minister   
73637             -1       11003167              Minister   
105561            -1       11002746        

In [203]:
datacube.head()

id  electoral_term  session        first_name last_name  \
45507  1045507              19        1  Dr. Hermann Otto     Solms   
45491  1045491              19        1             Bernd   Baumann   
45492  1045492              19        1  Dr. Hermann Otto     Solms   
45493  1045493              19        1               Jan     Korte   
45494  1045494              19        1  Dr. Hermann Otto     Solms   

       faction_id  politician_id           position_short    position_long  \
45507          -1       11002190  Presidium of Parliament  Alterspräsident   
45491          -1       11004662                Not found             None   
45492          -1       11002190  Presidium of Parliament  Alterspräsident   
45493          -1       11003790                Not found             None   
45494          -1       11002190  Presidium of Parliament  Alterspräsident   

                                          speech_content       date  
45507  \n\nHerr Präsident, ich darf Ihnen im Namen de... 2017-10-24  
45491  \n\nHerr Präsident! Meine Damen und Herren! Im... 2017-10-24  
45492  \n\nDas Wort hat jetzt der Kollege Jan Korte v... 2017-10-24  
45493  \n\nHerr Präsident! Liebe Kolleginnen und Koll... 2017-10-24  
45494  \n\nDas Wort hat jetzt Herr Kollege Michael Gr... 2017-10-24

In [210]:
politicians.head()

ui  electoral_term  faction_id abbreviation    first_name  \
0  11000198              19           5      CDU/CSU         Peter   
1  11000254              19          25          SPD      Eberhard   
2  11000365              19           7   DIE LINKE.  Jörg Diether   
3  11000365              19           7   DIE LINKE.       Diether   
4  11000616              19           5      CDU/CSU  Hans Joachim   

    last_name                 birth_place birth_country  birth_date  \
0      Bleser                Brachtendorf   Deutschland  23.07.1952   
1      Brecht  Quedlinburg / Bezirk Halle   Deutschland  20.02.1950   
2  Dehm-Desoi              Frankfurt/Main   Deutschland  03.04.1950   
3        Dehm              Frankfurt/Main   Deutschland  03.04.1950   
4     Fuchtel              Sulz am Neckar   Deutschland  13.02.1952   

  death_date    gender              profession academic_title  \
0         -1  männlich  Landwirtschaftsmeister            NaN   
1         -1  männlich          Dipl.-Physiker            Dr.   
2         -1  männlich  Autor, Geschäftsführer            Dr.   
3         -1  männlich  Autor, Geschäftsführer            Dr.   
4         -1  männlich    Parl. Staatssekretär            NaN   

  institution_type                                   institution_name  
0  Fraktion/Gruppe  Fraktion der Christlich Demokratischen Union/C...  
1  Fraktion/Gruppe  Fraktion der Sozialdemokratischen Partei Deuts...  
2  Fraktion/Gruppe                                Fraktion DIE LINKE.  
3  Fraktion/Gruppe                                Fraktion DIE LINKE.  
4  Fraktion/Gruppe  Fraktion der Christlich Demokratischen Union/C...

In [208]:
datacube.dtypes

id                         int64
electoral_term             int32
session                    int32
first_name                object
last_name                 object
faction_id                 int64
politician_id              int64
position_short            object
position_long             object
speech_content            object
date              datetime64[ns]
dtype: object

In [211]:
matches_count = datacube['politician_id'].isin(politicians['ui']).sum()

print(f"Total matches found: {matches_count}")

Total matches found: 118741


In [88]:
contributions_simplified = pd.read_pickle(f'{folder_path}contributions_simplified.pkl')
contributions_simplified["speech_id"] = contributions_simplified["speech_id"].astype(int)
contributions_simplified.head()

print(contributions_simplified["speech_id"].nunique())

print(len(contributions_simplified))

contributions_simplified[contributions_simplified["speech_id"] == 10]

338474
1966165


text_position                                      content  speech_id
0            4.0          (Unruhe. - Glocke des Präsidenten.)         10
1            3.0  (Heiterkeit. - Abg. Schütz: Ausgezeichnet!)         10
2            2.0           (Auszählen der Abstimmungskarten.)         10
3            1.0          (Einsammeln der Abstimmungskarten.)         10
4            0.0                                (Heiterkeit.)         10

In [91]:

# Read the pickle files again and give them new names
speech_content_filtered = pd.read_pickle(f'{folder_path}speech_content.pkl')
speech_content_filtered['date'] = pd.to_datetime(speech_content_filtered['date'], unit='s')
print(speech_content_filtered['id'].nunique())

# Check how many speeches and their ids are present in contributions_simplified df by performing inner join with speech content df 
merged_df = speech_content_filtered.merge(contributions_simplified, left_on='id', right_on='speech_id', how='inner')
print(merged_df['speech_id'].nunique())
#print(merged_df['speech_id'].unique())



967004
338474


In [94]:
# 1. Identifiziere die fehlenden speeches
missing_speeches_ids = speech_content[~speech_content['id'].isin(merged_df['speech_id'])]

# 2. Überprüfe die ersten paar Zeilen der fehlenden Reden
#print(missing_speeches_ids[['id', 'date', 'first_name', 'last_name', 'faction_id']].head())

# 3. Optional: Anzahl der fehlenden Reden
print(f'Anzahl reden in letzten beiden legislaturperioden: {len(speech_content)}')
print(f'Anzahl der Reden ohne Beiträge: {len(missing_speeches_ids)}')

# 4. Optional: Exportiere die fehlenden Reden in eine CSV-Datei
#missing_speeches_ids.to_csv('missing_speeches.csv', index=False)


Anzahl reden in letzten beiden legislaturperioden: 120318
Anzahl der Reden ohne Beiträge: 120318


In [83]:
contributions_simplified.dtypes

text_position    float64
content           object
speech_id        float64
dtype: object

In [84]:
contributions_simplified[contributions_simplified['speech_id'] == 1120313.0]

Empty DataFrame
Columns: [text_position, content, speech_id]
Index: []

In [61]:
contributions_simplified['content'].unique

<bound method Series.unique of 0                                             (Nellen)
0    (Nrn. 1800, zu 1800, 3300, zu 3300 der Drucksa...
1                                (Drucksache Nr. 3308)
0                               (Zurufe: Wiederholen!)
1                                    (Zurufe: Sofort!)
                           ...                        
2     (Henning Otte [CDU/CSU]: Haben Sie auch gesagt!)
3    (Beifall bei Abgeordneten der LINKEN Peter Bey...
4               (Peter Beyer [CDU/CSU]: Ja, wie denn?)
5    (Beifall bei Abgeordneten der LINKEN Peter Bey...
0    (Beifall bei der CDU/CSU sowie bei Abgeordnete...
Name: content, Length: 1966165, dtype: object>

In [189]:
politicians[(politicians['first_name'] == 'Lennard') & (politicians['last_name'] == 'Oehl')]

ui  electoral_term  faction_id first_name last_name  \
5791  11005170              20          25    Lennard      Oehl   

            birth_place birth_country  birth_date death_date    gender  \
5791  Frankfurt am Main   Deutschland  01.06.1993         -1  männlich   

     profession constituency aristocracy academic_title institution_type  \
5791  Volkswirt          NaN         NaN            NaN  Fraktion/Gruppe   

                                       institution_name    id abbreviation  
5791  Fraktion der Sozialdemokratischen Partei Deuts...  25.0          SPD

In [50]:
electoral_terms = pd.read_csv(f'{folder_path}electoral_terms.csv')
electoral_terms['start_date'] = pd.to_datetime(electoral_terms['start_date'], unit='s')
electoral_terms['end_date'] = pd.to_datetime(electoral_terms['end_date'], unit='s')
electoral_terms.tail()

# filter only 20 and 19 electoral terms

start_date   end_date  id
15 2005-10-18 2009-10-26  16
16 2009-10-27 2013-10-21  17
17 2013-10-22 2017-10-23  18
18 2017-10-24 2021-10-26  19
19 2021-10-27 2025-10-29  20

In [144]:
fractions = pd.read_pickle(f'{folder_path}factions.pkl')
fractions.head(40)

id           abbreviation  \
0    0                    AfD   
1    2                     BP   
2    4  Bündnis 90/Die Grünen   
3    7             DIE LINKE.   
4    9                 DP/DPB   
5   12                    DRP   
6    6                     DA   
7    8                     DP   
8   11                    DPB   
9    9                 DP/DPB   
10  10                 DP/FVP   
11  12                    DRP   
12  13                 DRP/NR   
13  28                      Z   
14   1                    BHE   
15   4  Bündnis 90/Die Grünen   
16   4  Bündnis 90/Die Grünen   
17  17                    FVP   
18  16                     FU   
19  19                 GB/BHE   
20  27                    WAV   
21  27                    WAV   
22   5                CDU/CSU   
23   5                CDU/CSU   
24  15                    FDP   
25  15                    FDP   
26  22                    KPD   
27  24                    PDS   
28  25                    SPD   
29  25                    SPD   
30  18           Fraktionslos   
31   3                    BSW   
32   4  Bündnis 90/Die Grünen   
33   8                     DP   
34   7             DIE LINKE.   
35  21                     KO   
36  24                    PDS   
37  24                    PDS   
38  26                    SSW   
39  20                   Gast   

                                         faction_name  
0                Fraktion Alternative für Deutschland  
1                               Fraktion Bayernpartei  
2                      Fraktion BÜNDNIS 90/DIE GRÜNEN  
3                                 Fraktion DIE LINKE.  
4                              Fraktion DP/DPB (Gast)  
5                                 Fraktion DRP (Gast)  
6          Fraktion Demokratische Arbeitsgemeinschaft  
7                            Fraktion Deutsche Partei  
8                     Fraktion Deutsche Partei Bayern  
9     Fraktion Deutsche Partei/Deutsche Partei Bayern  
10         Fraktion Deutsche Partei/Freie Volkspartei  
11                     Fraktion Deutsche Reichspartei  
12    Fraktion Deutsche Reichspartei/Nationale Rechte  
13                  Fraktion Deutsche Zentrums-Partei  
14  Fraktion Deutscher Gemeinschaftsblock der Heim...  
15                                Fraktion Die Grünen  
16                     Fraktion Die Grünen/Bündnis 90  
17                         Fraktion Freie Volkspartei  
18                     Fraktion Föderalistische Union  
19  Fraktion Gesamtdeutscher Block / Block der Hei...  
20                                Fraktion WAV (Gast)  
21         Fraktion Wirtschaftliche Aufbauvereinigung  
22                        Fraktion der CDU/CSU (Gast)  
23  Fraktion der Christlich Demokratischen Union/C...  
24                            Fraktion der FDP (Gast)  
25          Fraktion der Freien Demokratischen Partei  
26   Fraktion der Kommunistischen Partei Deutschlands  
27  Fraktion der Partei des Demokratischen Soziali...  
28                            Fraktion der SPD (Gast)  
29  Fraktion der Sozialdemokratischen Partei Deuts...  
30                                       Fraktionslos  
31  Gruppe BSW - Bündnis Sahra Wagenknecht - Vernu...  
32                       Gruppe Bündnis 90/Die Grünen  
33                             Gruppe Deutsche Partei  
34                                   Gruppe Die Linke  
35                            Gruppe Kraft/Oberländer  
36   Gruppe der Partei des Demokratischen Sozialismus  
37  Gruppe der Partei des Demokratischen Sozialism...  
38                    Südschleswigscher Wählerverband  
39                                               Gast

In [150]:
party = fractions[['id', 'abbreviation']].drop_duplicates()
party.head(20)

id           abbreviation
0    0                    AfD
1    2                     BP
2    4  Bündnis 90/Die Grünen
3    7             DIE LINKE.
4    9                 DP/DPB
5   12                    DRP
6    6                     DA
7    8                     DP
8   11                    DPB
10  10                 DP/FVP
12  13                 DRP/NR
13  28                      Z
14   1                    BHE
17  17                    FVP
18  16                     FU
19  19                 GB/BHE
20  27                    WAV
22   5                CDU/CSU
24  15                    FDP
26  22                    KPD

In [109]:
# Group by 'electoral_term' and calculate min and max 'id'
min_max_ids = speech_content.groupby('electoral_term')['id'].agg(['min', 'max', 'nunique']).reset_index()

# Display the results
print(min_max_ids)


    electoral_term      min      max  nunique
0                1        0    28905    28906
1                2    28906    54986    26081
2                3    54987    77809    22823
3                4    77810   119022    41213
4                5   119023   173129    54107
5                6   173130   208704    35575
6                7   208705   266036    57332
7                8   266037   318338    52302
8                9   318339   349013    30675
9               10   349014   413882    64869
10              11   413883   471525    57643
11              12   471526   529560    58035
12              13   529561   587029    57469
13              14   587030   640545    53516
14              15   640546   677451    36906
15              16   677452   729469    52018
16              17   729470   794025    64556
17              18   794026   846685    52660
18              19  1000000  1064024    64025
19              20  1064025  1120317    56293


In [112]:
# Building speech datacube 

# each speaker:
# - party (politicians table)
# - fraction (yes no which one)
# - member of parliament yes / no "MDB"
# - electoral term (electoral_terms table)
# 

# contributions kategorisieren (wie viel beifall, wie viele zwischenrufe...)

#print(len(speech_content))
datacube = speech_content[speech_content['electoral_term'].isin([19, 20])]
#datacube.sample(5)

p18 = datacube = speech_content[speech_content['electoral_term'].isin([19])]
print(p18['date'].min(), p18['date'].max())
print(p18['id'].min(), p18['id'].max())
print(p18['session'].min(), p18['session'].max())
print(p18['id'].nunique())
#p18.head()


#print(len(speech_content))
#len(speech_content.iloc[0, 10])
# speichere 20 random rows in ein excel file
#speech_content.sample(20).to_excel('speech_content_sample.xlsx')



2017-10-24 00:00:00 2021-09-07 00:00:00
1000000 1064024
1 239
64025


id  electoral_term  session                   first_name  \
45488  1045488              19        1  Alterspräsident Dr. Hermann   
52891  1052891              19       22                 Dr. Wolfgang   
46356  1046356              19       30                        Sarah   
7281   1007281              19       35                     Wolfgang   
52471  1052471              19       41                       Thomas   

        last_name  faction_id  politician_id           position_short  \
45488  Otto Solms          -1       11002190  Presidium of Parliament   
52891    Schäuble          -1       11001938  Presidium of Parliament   
46356   Ryglewski          25       11004622     Member of Parliament   
7281      Kubicki          -1       11001235  Presidium of Parliament   
52471   Oppermann          -1       11003820  Presidium of Parliament   

         position_long speech_content       date  
45488  Alterspräsident                2017-10-24  
52891        Präsident                2018-03-21  
46356             None                2018-04-27  
7281     Vizepräsident                2018-06-06  
52471    Vizepräsident                2018-06-27

In [134]:
datacube.head()

id  electoral_term  session                   first_name  \
45504  1045504              19        1  Alterspräsident Dr. Hermann   
45505  1045505              19        1             Dr. Hermann Otto   
45506  1045506              19        1                     Wolfgang   
45507  1045507              19        1             Dr. Hermann Otto   
45508  1045508              19        1                 Dr. Wolfgang   

        last_name  faction_id  politician_id           position_short  \
45504  Otto Solms          -1       11002190  Presidium of Parliament   
45505       Solms          -1       11002190  Presidium of Parliament   
45506    Schäuble           5       11001938     Member of Parliament   
45507       Solms          -1       11002190  Presidium of Parliament   
45508    Schäuble          -1       11002190  Presidium of Parliament   

         position_long                                     speech_content  \
45504  Alterspräsident  \n\nDas ist der Fall. – Ich sehe keine weitere...   
45505  Alterspräsident  \n\nDie unterbrochene Sitzung ist wieder eröff...   
45506             None  \n\nHerr Präsident, ich nehme die Wahl an.\n\n...   
45507  Alterspräsident  \n\nHerr Präsident, ich darf Ihnen im Namen de...   
45508        Präsident  \n\nHerr Bundespräsident! Verehrte Kolleginnen...   

            date  
45504 2017-10-24  
45505 2017-10-24  
45506 2017-10-24  
45507 2017-10-24  
45508 2017-10-24

In [76]:
speech_content.iloc[0, :]

id                                                          1000000
electoral_term                                                   19
session                                                         123
first_name                                                    Heiko
document_url      https://dip21.bundestag.de/dip21/btp/19/19123.pdf
last_name                                                      Maas
faction_id                                                       -1
position_short                                             Minister
position_long                        Bundesminister des Auswärtigen
politician_id                                              11004809
speech_content    \n\nVielen Dank, Herr Präsident. – Liebe Kolle...
date                                            2019-11-06 00:00:00
Name: 0, dtype: object

In [72]:
print(str(speech_content.iloc[0, 10]))



Vielen Dank, Herr Präsident. – Liebe Kolleginnen und Kollegen! Meine sehr verehrten Damen und Herren! In den letzten Tagen und Wochen wird ja viel über deutsche und europäische Verantwortung diskutiert. Deshalb ist es vielleicht eine gute Gelegenheit, auf eine Region hinzuweisen, in der sowohl die deutsche als auch die europäische Verantwortung gerade jetzt gefordert sind. Ein Gradmesser dabei wird sein, ob es uns als Europäern gelingt, die unmittelbare Nachbarschaft zu stabilisieren und dabei internationale Partner einzubinden, aber auch, dies mit internationalen Organisationen zu koordinieren. Die Region, auf die das zutrifft, ist Nordafrika.

Die arabischen Umbrüche von 2011 haben dort vor Ort völlig unterschiedliche Situationen hinterlassen. Wir erleben Tunesien als eine lebendige Demokratie, was die dort gerade erfolgten Wahlen noch einmal unter Beweis gestellt haben. In Libyen haben wir es mit einem zerfallenen Staat zu tun, in Ägypten mit einem außerordentlich straff und autor

In [70]:
print(speech_content.iloc[0, 10])



Vielen Dank, Herr Präsident. – Liebe Kolleginnen und Kollegen! Meine sehr verehrten Damen und Herren! In den letzten Tagen und Wochen wird ja viel über deutsche und europäische Verantwortung diskutiert. Deshalb ist es vielleicht eine gute Gelegenheit, auf eine Region hinzuweisen, in der sowohl die deutsche als auch die europäische Verantwortung gerade jetzt gefordert sind. Ein Gradmesser dabei wird sein, ob es uns als Europäern gelingt, die unmittelbare Nachbarschaft zu stabilisieren und dabei internationale Partner einzubinden, aber auch, dies mit internationalen Organisationen zu koordinieren. Die Region, auf die das zutrifft, ist Nordafrika.

Die arabischen Umbrüche von 2011 haben dort vor Ort völlig unterschiedliche Situationen hinterlassen. Wir erleben Tunesien als eine lebendige Demokratie, was die dort gerade erfolgten Wahlen noch einmal unter Beweis gestellt haben. In Libyen haben wir es mit einem zerfallenen Staat zu tun, in Ägypten mit einem außerordentlich straff und autor

## Datasets not needed 

In [135]:
plenarprotokoll_reden = pd.read_csv(f'{folder_path}plenarprotokoll_reden.csv')
plenarprotokoll_reden.tail()

# check later disregard for now 

redner_name  \
364  Antwort der Parl. Staatssekretärin Daniela Klu...   
365  Antwort der Parl. Staatssekretärin Daniela Klu...   
366  Antwort der Parl. Staatssekretärin Daniela Klu...   
367  Antwort der Parl. Staatssekretärin Dr. Bettina...   
368  Antwort des Parl. Staatssekretärs Mario Brande...   

                                             rede_text  vorname  \
364  Die Bundesregierung setzt sich für verbraucher...  Antwort   
365  Der Entwurf des Digitale-Dienste-Gesetzes befi...  Antwort   
366  Das Vorhaben W 38, „Vorgezogener Ersatz dreier...  Antwort   
367  Nach den der Bundesregierung vorliegenden Info...  Antwort   
368  Das Forum #Zukunftsstrategie besteht aus 21 Ex...  Antwort   

                                            nachname  wortanzahl  
364      der Parl. Staatssekretärin Daniela Kluckert         158  
365      der Parl. Staatssekretärin Daniela Kluckert          98  
366      der Parl. Staatssekretärin Daniela Kluckert         127  
367  der Parl. Staatssekretärin Dr. Bettina Hoffmann         200  
368      des Parl. Staatssekretärs Mario Brandenburg         180

In [46]:
data_cube = pd.read_pickle(f'{folder_path}data_cube.pkl')
data_cube.ndim

# 7 dimensions nparray ?? 

7

In [47]:
weight_cube = pd.read_pickle(f'{folder_path}weight_cube.pkl')
weight_cube.ndim

# 7 dimensions nparray ??

7

In [56]:
politician_weight_cube = pd.read_pickle(f'{folder_path}politician_weight_cube.pkl')
politicians.ndim

print(politician_weight_cube[:5, :5])

[[[22. 17. 25. ...  0.  0.  0.]
  [ 0.  0.  0. ...  0.  0.  0.]
  [ 0.  0.  0. ...  0.  0.  0.]
  [ 3. 13. 13. ...  0.  0.  0.]
  [ 0.  0.  0. ...  0.  0.  0.]]

 [[22. 17. 25. ...  0.  0.  0.]
  [ 0.  0.  0. ...  0.  0.  0.]
  [ 0.  0.  0. ...  0.  0.  0.]
  [ 3. 13. 13. ...  0.  0.  0.]
  [ 0.  0.  0. ...  0.  0.  0.]]

 [[22. 17. 25. ...  0.  0.  0.]
  [ 0.  0.  0. ...  0.  0.  0.]
  [ 0.  0.  0. ...  0.  0.  0.]
  [ 3. 13. 13. ...  0.  0.  0.]
  [ 0.  0.  0. ...  0.  0.  0.]]

 [[22. 17. 25. ...  0.  0.  0.]
  [ 0.  0.  0. ...  0.  0.  0.]
  [ 0.  0.  0. ...  0.  0.  0.]
  [ 3. 13. 13. ...  0.  0.  0.]
  [ 0.  0.  0. ...  0.  0.  0.]]

 [[22. 17. 25. ...  0.  0.  0.]
  [ 0.  0.  0. ...  0.  0.  0.]
  [ 0.  0.  0. ...  0.  0.  0.]
  [ 3. 13. 13. ...  0.  0.  0.]
  [ 0.  0.  0. ...  0.  0.  0.]]]


In [36]:
politician_data_cube = pd.read_pickle(f'{folder_path}politician_data_cube.pkl')
politician_data_cube.ndim
print(politician_data_cube[:5, :5, :5])

[[[0.06085636 0.04647865 0.01995937 0.03171199 0.01612579]
  [       nan        nan        nan        nan        nan]
  [       nan        nan        nan        nan        nan]
  [0.0073117  0.04325641 0.02143461 0.02981574 0.05460114]
  [       nan        nan        nan        nan        nan]]

 [[0.03087719 0.09849169 0.04718056 0.03906541 0.05192385]
  [       nan        nan        nan        nan        nan]
  [       nan        nan        nan        nan        nan]
  [0.02042468 0.04736717 0.02076439 0.07237773 0.05988932]
  [       nan        nan        nan        nan        nan]]

 [[0.00821595 0.01733447 0.00773253 0.00917325 0.00212615]
  [       nan        nan        nan        nan        nan]
  [       nan        nan        nan        nan        nan]
  [0.00233974 0.00945677 0.01546901 0.0076168  0.00367307]
  [       nan        nan        nan        nan        nan]]

 [[0.03086216 0.00485641 0.00226627 0.01168779 0.00564218]
  [       nan        nan        nan        nan    

In [24]:
dims = pd.read_pickle(f'{folder_path}dims.pkl')

# Get the first 2 elements from the list
first_few_items = dict(list(dims.items())[:2])

# Pretty-print the subset with proper structure
print(json.dumps(first_few_items, indent=4))

{
    "topics": [
        [
            "topic_0",
            "Volkswirtschaft"
        ],
        [
            "topic_1",
            "B\u00fcrger:Innenrechte"
        ],
        [
            "topic_2",
            "Gesundheitswesen"
        ],
        [
            "topic_3",
            "Landwirtschaft"
        ],
        [
            "topic_4",
            "Arbeit"
        ],
        [
            "topic_5",
            "Bildung"
        ],
        [
            "topic_6",
            "Umwelt"
        ],
        [
            "topic_7",
            "Energie"
        ],
        [
            "topic_8",
            "Transport"
        ],
        [
            "topic_9",
            "Recht & Kriminalit\u00e4t"
        ],
        [
            "topic_10",
            "Sozialpolitik"
        ],
        [
            "topic_11",
            "Wohnungswesen"
        ],
        [
            "topic_12",
            "Binnenhandel"
        ],
        [
            "topic_13",
            

In [52]:
politician_dims = pd.read_pickle(f'{folder_path}politician_dims.pkl')

# Get the first 2 elements from the list
first_few_items = dict(list(politician_dims.items())[:2])

# Pretty-print the subset with proper structure
print(json.dumps(first_few_items, indent=4))

{
    "topics": [
        [
            "topic_0",
            "Volkswirtschaft"
        ],
        [
            "topic_1",
            "B\u00fcrger:Innenrechte"
        ],
        [
            "topic_2",
            "Gesundheitswesen"
        ],
        [
            "topic_3",
            "Landwirtschaft"
        ],
        [
            "topic_4",
            "Arbeit"
        ],
        [
            "topic_5",
            "Bildung"
        ],
        [
            "topic_6",
            "Umwelt"
        ],
        [
            "topic_7",
            "Energie"
        ],
        [
            "topic_8",
            "Transport"
        ],
        [
            "topic_9",
            "Recht & Kriminalit\u00e4t"
        ],
        [
            "topic_10",
            "Sozialpolitik"
        ],
        [
            "topic_11",
            "Wohnungswesen"
        ],
        [
            "topic_12",
            "Binnenhandel"
        ],
        [
            "topic_13",
            